### ISSUE TITLE
Incorrect panning when use focal zoom

### ISSUE THREAD

**Issue by lamartire** [timmywil/panzoom#268]
### Subject of the issue

When I trying to zoom child element with **100% width** of parent, it jump to bottom-right or top-left angle.
 How I can zoom similar elements without this trouble?
### Your environment
- **jquery.panzoom 3.2.1**
- **jquery 2.2.4**
- **All modern browsers**
### Steps to reproduce

[Reproducing of problem](http://codepen.io/lamartire/pen/grEPAq)
### Expected behaviour

Like [this](http://timmywil.github.io/jquery.panzoom/demo/#focal)
Content must zoom correctly without "jumpimg".
### Actual behaviour

Look at _Steps to reproduce_

**Comment by hunterSThompson** [comment]
I ran into this too.

I think what's happening is every time you zoom in, the mouse's position _relative to the panzoom div_ changes, so on your next mousewheel scroll your focal point is different.  Not sure why this doesn't happen on the demo...

I solved by passing: `focal: { clientX: e.pageX, clientY: e.pageY }` from the mousewheel event.

**Comment by theahura** [comment]
Having the same problem, but the above suggestion did not fix it.

**Comment by borealissw** [comment]
Essentially the same as issue [331](https://github.com/timmywil/jquery.panzoom/issues/331). The issue boils down to problems with animation being set. Workaround is to set animate: false in options.

See [my comment](https://github.com/timmywil/jquery.panzoom/issues/331#issuecomment-350329970) for the issue.
